### ISSUE TITLE
"Arg too small" on info requests with 1 letter

### ISSUE THREAD

**Issue by AladW** [moson-mo/goaurrpc#1]
When using upstream aurweb, a request such as
```
curl 'https://aur.archlinux.org/rpc?v=5&type=inf&arg[]=r' 
```
leads to:
```
{"resultcount":0,"results":[],"type":"multiinfo","version":5}
```
However, with goaurrpc (using the server.moson.rocks/rpc instance) I have:
```
{"error":"Query arg too small.","resultcount":0,"results":[],"type":"error","version":5c
```
This is the behavior aurweb would have when a 1-character search is done. However, for info-type requests having a single-letter term is valid, as package names may consist of 1 letter.

**Comment by moson-mo** [comment]
Hi @AladW 

Thanks for noticing. This is fixed now.

**Comment by moson-mo** [comment]
Thanks for reporting. I'll check it end of this week.
