### ISSUE TITLE
Expose prometheous metrics over /metrics

### ISSUE THREAD

**Issue by inglor** [moson-mo/goaurrpc#4]
As per title

**Comment by moson-mo** [comment]
Hey @inglor, I've added some basic Prometheus metrics with https://github.com/moson-mo/goaurrpc/commit/f24031534c4918760051fe5c484db652cd5291a1 

If you have ideas for other metrics, let me know. 😉

**Comment by moson-mo** [comment]
Implemented in [v1.1.2](https://github.com/moson-mo/goaurrpc/releases/tag/v1.1.2)
